USE spitter;

DROP TABLE Device;
DROP TABLE House;
DROP TABLE Person;

CREATE TABLE IF NOT EXISTS Person (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  `age` TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS House (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `owner_id` INT(11),
  `size` TINYINT NOT NULL,
  `location` VARCHAR(50) NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Device (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `owner_id` INT(11),
  `name` VARCHAR(20) NOT NULL,
  `type` TINYINT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE 
);

