USE spitter;

DROP TABLE Device;
DROP TABLE House;
DROP TABLE Person;

CREATE TABLE IF NOT EXISTS Person (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  `age` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS House (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `owner_id` INT(11),
  `size` TINYINT NOT NULL,
  `location` VARCHAR(50) NOT NULL,
  `ip_address` VARBINARY(16) NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Device (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `owner_id` INT(11),
  `name` VARCHAR(20) NOT NULL,
  `type` TINYINT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS Gateway (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DeviceList (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS Machine (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `name` VARCHAR(20),
  `gateway_id` INT
);

CREATE TABLE IF NOT EXISTS DeviceList_Machine (
  `devicelist_id` INT,
  `machine_id` INT
);