DROP TABLE IF EXISTS Blog;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Post;

CREATE TABLE Blog
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  author_id INT NOT NULL,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE Author
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  favourite_section VARCHAR(25) NOT NULL
);

CREATE TABLE Post
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  blog_id INT NOT NULL,
  author_id INT NOT NULL,
  created_time TIMESTAMP NOT NULL,
  section VARCHAR(25) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  draft BOOLEAN NOT NULL
);